#!/usr/bin/env bash
# Installs HAProxy with the following configurations:
# - Enables management via the init script.
# - Distributes requests using a round-robin algorithm.

sudo apt-get install -y haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend next.tech
    timeout client  30000
    bind 0:80
    default_backend next.tech_backend

backend next.tech_backend
    timeout connect  3000
    timeout server  30000
    balance roundrobin
    server 480459-web-01 100.26.228.133:80 check
    server 480459-web-02 54.242.169.80:80 check
EOT

sudo service haproxy restart
